name: Test & release dist files

on:
   push:
     branches:
       - main
     paths:
       - 'dist/**'
  
   pull_request:
     branches:
       - main
     paths:
       - 'dist/**'
   
jobs:
  npm-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        
      - uses: actions/setup-node@v3
        env:
         PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'

      - name: npm install and test
        run: |
         npm ci
         npm test
         
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
        
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
        
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"

  release-github:
    needs: npm-test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v3
      - run: |
           git config --global user.email "bot_${{ github.event_name }}@users.noreply.github.com"
           git config --global user.name "bot_${{ github.event_name }}"
           
      - uses: actions/setup-node@v3
        env:
         PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      - run: npm ci
      - run: npm run release -- patch --ci
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT"
        
      - name: Dump job context
        env:
          JOB_CONTEXT: ${{ toJson(job) }}
        run: echo "$JOB_CONTEXT"
        
      - name: Dump steps context
        env:
          STEPS_CONTEXT: ${{ toJson(steps) }}
        run: echo "$STEPS_CONTEXT"
        
      - name: Dump runner context
        env:
          RUNNER_CONTEXT: ${{ toJson(runner) }}
        run: echo "$RUNNER_CONTEXT"
