name: Make release and test it

on:
   push:
     branches:
       - main

   pull_request:
     branches:
       - main
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        
      - uses: actions/setup-node@v1
        env:
         PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      - run: npm ci
      - run: npm test

  release-github:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push'
    steps:
      - uses: actions/checkout@v2
      - run: |
           git config --global user.email "bot_${{ github.event_name }}@users.noreply.github.com"
           git config --global user.name "bot_${{ github.event_name }}"
           
      - uses: actions/setup-node@v1
        env:
         PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: 'true'
      - run: npm ci
      - run: npm run release -- minor --ci
        env:
          GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}
