# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: Scrape all site to a pull request!

on:
  push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
    paths: 
      - .github/workflows/scrape-all-to-pr.js.yml

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2

    - name: Create .env file
      run: |
          touch .env
          echo LOGBUY_USER=${{ secrets.LOGBUY_USER }} >> .env
          echo LOGBUY_PASS=${{ secrets.LOGBUY_PASS }} >> .env
          cat .env
      
    - name: Node install and run
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run index all --if-present
    - run: npm test --if-present

    - name: Create Pull Request # Does so only if any files in repo have changed
      uses: peter-evans/create-pull-request@v3
      with:
        # token: ${{ secrets.PAT }}
        commit-message: New scrape
        committer: bot_${{ github.event_name }} <bot_${{ github.event_name }}@users.noreply.github.com>
        # author cant be changed from owner when using PAT issue#48
        branch: auto-new-scrape
        delete-branch: true
        title: New scrape
        body: |
          New scrape performed

          - Auto-generated by [create-pull-request][1]

          [1]: https://github.com/peter-evans/create-pull-request
        labels: auto-pr
