name: Scrape all sites and make a pull request

on:
  push:
    branches: [ zinen-patch-1 ]
    paths: 
      - .github/workflows/scrape-all-to-pr.js.yml
  pull_request:
    branches: [ zinen-patch-1 ]

  workflow_dispatch:

jobs:

  make-dist:
    if: ${{ always() }} # Perform this step no matter any errors
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v3

    - name: Node install and run
      uses: actions/setup-node@v3
    - run: |
        npm ci
        node . dist
        npm run analyzeLastScrape

    - name: Collect log files to make body for pull request
      id: get-pr-body
      run: |
        outputFile=./logs/report.log
        # Run script
        node ./utils/make-auto-pr-body.js $outputFile
        cat $outputFile
        # Define pull request body to be used in laster steps
        pr_body=$( cat $outputFile )
        # Replace some badly handled characters with Unicode characters
        pr_body="${pr_body//'%'/'%25'}"
        pr_body="${pr_body//$'\n'/'%0A'}"
        pr_body="${pr_body//$'\r'/'%0D'}" 
        # Save variable as an output
        echo "body=$pr_body" >> $GITHUB_OUTPUT

    - name: Create Pull Request # Does so only if any files in repo have changed
      uses: peter-evans/create-pull-request@v4
      with:
        token: ${{ secrets.MY_GITHUB_PAT }}
        commit-message: New scrape
        committer: bot_${{ github.event_name }} <bot_${{ github.event_name }}@users.noreply.github.com>
        # author cant be changed from owner when using PAT issue#48
        branch: auto-new-scrape
        delete-branch: true
        title: New scrape
        body: |
          New scrape performed
          
          ${{ steps.get-pr-body.outputs.body }}

          *Auto-generated by [create-pull-request][1]*

          [1]: https://github.com/peter-evans/create-pull-request
        labels: test
