name: Scrape all sites and make a pull request

on:
#   push:
#     branches: [ master ]
#   pull_request:
#     branches: [ master ]
#     paths: 
#       - .github/workflows/scrape-all-to-pr.js.yml

  schedule:
    - cron:  '15 2 3 * *'

jobs:
  scrape:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2

    - name: Create .env file
      run: |
          touch .env
          echo 'LOGBUY_USER=${{ secrets.LOGBUY_USER }}' >> .env
          echo 'LOGBUY_PASS=${{ secrets.LOGBUY_PASS }}' >> .env
          cat .env
      
    - name: Node install and run
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: npm ci
    - run: npm run index all
    - run: npm run analyseLastScrape

    - name: Collect log files to make body for pull request
      id: get-pr-body
      run: |
        touch trigger
        outputFile=./logs/report.log
        # Delete and make a new file
        rm -f $outputFile
        touch $outputFile
        #
        inputFile=./logs/analyse-aeldresagen.log
        countNewFile=$( cat $inputFile | jq -r "._analyse.countNewFile" )
        countAdded=$( cat $inputFile | jq -r "._analyse.countAdded" )
        countRemoved=$( cat $inputFile | jq -r "._analyse.countRemoved" )
        echo " - **aeldresagen** - total entries $countNewFile (new $countAdded / removed $countRemoved)">> $outputFile
        #
        inputFile=./logs/analyse-coop.log
        countNewFile=$( cat $inputFile | jq -r "._analyse.countNewFile" )
        countAdded=$( cat $inputFile | jq -r "._analyse.countAdded" )
        countRemoved=$( cat $inputFile | jq -r "._analyse.countRemoved" )
        echo " - **coop** - total entries $countNewFile (new $countAdded / removed $countRemoved)">> $outputFile
        #
        inputFile=./logs/analyse-forbrugsforeningen.log
        countNewFile=$( cat $inputFile | jq -r "._analyse.countNewFile" )
        countAdded=$( cat $inputFile | jq -r "._analyse.countAdded" )
        countRemoved=$( cat $inputFile | jq -r "._analyse.countRemoved" )
        echo " - **forbrugsforeningen** - total entries $countNewFile (new $countAdded / removed $countRemoved)">> $outputFile
        #
        inputFile=./logs/analyse-logbuy.log
        countNewFile=$( cat $inputFile | jq -r "._analyse.countNewFile" )
        countAdded=$( cat $inputFile | jq -r "._analyse.countAdded" )
        countRemoved=$( cat $inputFile | jq -r "._analyse.countRemoved" )
        echo " - **logbuy** - total entries $countNewFile (new $countAdded / removed $countRemoved)">> $outputFile
        cat $outputFile
        # Define pull request body to be used in laster steps
        pr_body=$( cat $outputFile )
        pr_body="${pr_body//'%'/'%25'}"
        pr_body="${pr_body//$'\n'/'%0A'}"
        pr_body="${pr_body//$'\r'/'%0D'}" 
        echo ::set-output name=body::$pr_body

    - name: Create Pull Request # Does so only if any files in repo have changed
      uses: peter-evans/create-pull-request@v3
      with:
        # token: ${{ secrets.PAT }}
        commit-message: New scrape
        committer: bot_${{ github.event_name }} <bot_${{ github.event_name }}@users.noreply.github.com>
        # author cant be changed from owner when using PAT issue#48
        branch: auto-new-scrape
        delete-branch: true
        title: New scrape
        body: |
          New scrape performed
          
          ${{ steps.get-pr-body.outputs.body }}

          *Auto-generated by [create-pull-request][1]*

          [1]: https://github.com/peter-evans/create-pull-request
        labels: auto-pr

    - name: Save npm failure logs as artifact
      if: ${{ failure() }} # Perform this step if some error happened
      uses: actions/upload-artifact@v2
      with:
        name: npm-logs
        path: |
          /home/runner/.npm/_logs/*
  
    - name: Save logs as artifact
      if: ${{ always() }} # Perform this step no mattter any errors
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: |
          ./logs/*
