name: Scrape all sites and make a pull request

on:
#   push:
#     branches: [ main ]
  pull_request:
    branches: [ main ]
    paths: 
      - .github/workflows/scrape-all-to-pr.js.yml

  schedule:
    - cron:  '15 2 3 * *'
    

jobs:

  scrape:
    strategy:
      # Don't cancel the other jobs if one fails
      fail-fast: false
      matrix:
        include: 
          - discount-service: 'forbrugsforeningen'
            store-scrapes: './scraped-data/forb'
            artifact-name: 'forbrugsforeningen-artifact'
            artifact-name-failure: 'forbrugsforeningen-npm-logs'
          - discount-service: 'logbuy'
            store-scrapes: './scraped-data/logb'
            artifact-name: 'logbuy-artifact'
            artifact-name-failure: 'logbuy-npm-logs'
          - discount-service: 'coop'
            store-scrapes: './scraped-data/coop'
            artifact-name: 'coop-artifact'
            artifact-name-failure: 'coop-npm-logs'
          - discount-service: 'aeldresagen'
            store-scrapes: './scraped-data/aeld'
            artifact-name: 'aeldresagen-artifact'
            artifact-name-failure: 'aeldresagen-npm-logs'
            
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2

    - name: Create .env file
      run: |
          touch .env
          echo 'LOGBUY_USER=${{ secrets.LOGBUY_USER }}' >> .env
          echo 'LOGBUY_PASS=${{ secrets.LOGBUY_PASS }}' >> .env
          cat .env
      
    - name: Node install and run
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: |
        npm ci
        node . ${{ matrix.discount-service }}

    - name: Save npm failure logs as artifact
      if: ${{ failure() }} # Perform this step if some error happened
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.artifact-name-failure}}
        path: |
          /home/runner/.npm/_logs/*

    - name: temporarily save scrape data to artifact
      uses: actions/upload-artifact@v2
      with:
        name: ${{ matrix.artifact-name}}
        path: ${{ matrix.store-scrapes}}
        retention-days: 1

  make-dist:
    if: ${{ always() }} # Perform this step no matter any errors
    needs: scrape
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v2

    - name: get artifact from forbrugsforeningen scrape run
      uses: actions/download-artifact@master
      with:
        name: forbrugsforeningen-artifact
        path: ./scraped-data/forb

    - name: get artifact from logbuy scrape run
      uses: actions/download-artifact@master
      with:
        name: logbuy-artifact
        path: ./scraped-data/logb

    - name: get artifact from coop scrape run
      uses: actions/download-artifact@master
      with:
        name: coop-artifact
        path: ./scraped-data/coop

    - name: get artifact from aeldresagen scrape run
      uses: actions/download-artifact@master
      with:
        name: aeldresagen-artifact
        path: ./scraped-data/aeld


    - name: Node install and run
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    - run: |
        npm ci
        node . dist
        npm run analyseLastScrape

    - name: Collect log files to make body for pull request
      id: get-pr-body
      run: |
        outputFile=./logs/report.log
        # Run script
        node ./utils/make-auto-pr-body.js $outputFile
        cat $outputFile
        # Define pull request body to be used in laster steps
        pr_body=$( cat $outputFile )
        # Replace some badly handled characters with Unicode characters
        pr_body="${pr_body//'%'/'%25'}"
        pr_body="${pr_body//$'\n'/'%0A'}"
        pr_body="${pr_body//$'\r'/'%0D'}" 
        # Save variable as an output
        echo ::set-output name=body::$pr_body

    - name: temporarily made dist files artifact
      uses: actions/upload-artifact@v2
      with:
        name: dist-artifact
        path: ./dist
        retention-days: 1

    - name: temporarily scrape files artifact
      uses: actions/upload-artifact@v2
      with:
        name: scraped-data-artifact
        path: ./scraped-data
        retention-days: 1

    # - name: Create Pull Request # Does so only if any files in repo have changed
    #   uses: peter-evans/create-pull-request@v3
    #   with:
    #     token: ${{ secrets.MY_GITHUB_PAT }}
    #     commit-message: New scrape
    #     committer: bot_${{ github.event_name }} <bot_${{ github.event_name }}@users.noreply.github.com>
    #     # author cant be changed from owner when using PAT issue#48
    #     branch: auto-new-scrape
    #     delete-branch: true
    #     title: New scrape
    #     body: |
    #       New scrape performed
          
    #       ${{ steps.get-pr-body.outputs.body }}

    #       *Auto-generated by [create-pull-request][1]*

    #       [1]: https://github.com/peter-evans/create-pull-request
    #     labels: auto-pr
    #     assignees: zinen
        
    - name: Save logs as artifact
      if: ${{ failure() }} # Perform this step if some error happened
      uses: actions/upload-artifact@v2
      with:
        name: logs
        path: |
          ./logs/*